language: ruby
# only run CI-builds on travis-ci branch
branches:
  only:
  - travis-ci
rvm:
- 2.4.2
# set execution permission on our build script
before_script:
 - chmod +x ./script/cibuild
# path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./script/cibuild
exclude: [vendor]
sudo: false
